### ISSUE TITLE
Limit the window/side panel minimum size.

### ISSUE THREAD

**Issue by HatWearingMann** [IohannRabeson/teamwork-launcher#106]
**I feel like the user is currently given a little too much freedom with the window resizing:**

![image](https://user-images.githubusercontent.com/79970290/224519299-fdc1ea45-9fd4-49b1-b2d0-239708170816.png) ![image](https://user-images.githubusercontent.com/79970290/224519313-a8229ba9-ae17-4c44-a871-2ca3566d9e53.png)

**As for the server list part, perhaps the entries could become more compact on the most extreme resizes:**

![mockup](https://user-images.githubusercontent.com/79970290/224519720-6fdae1df-283e-4324-975e-5238661a69d9.png)

**And the settings side panel should be limited to right around this:**

![image](https://user-images.githubusercontent.com/79970290/224519781-caa22542-a614-4d4b-bf39-708fe6e18f12.png)

**Comment by IohannRabeson** [comment]
Thanks for the mockup, this definitely make sense!

**Comment by IohannRabeson** [comment]
Hey, I worked a bit on this task, I named this mode the compact mode, based on your mockup!
![image](https://user-images.githubusercontent.com/685196/224579712-a34ec165-2110-4327-8bce-a8f5d0f61ed8.png)

**Comment by HatWearingMann** [comment]
I don't think this is completed, as the window resizing issue was not yet addressed, just the in-window sidebar adjustment was.

**Comment by HatWearingMann** [comment]
Please unclose this until it is fixed :)

**Comment by IohannRabeson** [comment]
I can't decide the window size, the user can do whatever he wants with the window and I can't prevent that.
